name: Build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Commit and Push Changes
        run: |
          sed -i "s|gassouma530975/testdeploy:*|gassouma530975/testdeploy:back-${{github.sha}}|" manifests/back.yaml
          # configure user
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          # stage any file changes to be committed
          git add .

          # make commit with staged changes
          git commit -m 'files changed'

          # push the commit back up to source GitHub repository
          git push https://x-access-token:${{ secrets.PAT }}@github.com/samiagassouma/testDeploy.git HEAD:main
