name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}


      # - name: Run Trivy scan on Docker image
      #   uses: aquasecurity/trivy-action@0.28.0
      #   with:
      #     scan-type: image
      #     image-ref: 'docker.io/gassouma530975/myapp:v3'
      #     format: table
      #     output: trivy-image.txt
      #     ignore-unfixed: true
      #     vuln-type: "os,library"
        
      # - name: Upload Trivy image report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: trivy-image-report
      #     path: trivy-image.txt

      # - name: Show Trivy image report
      #   run: cat trivy-image.txt
