name: Build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Commit and Push Changes
        run: |
          sed -i "s|gassouma530975/testdeploy:*|gassouma530975/testdeploy:back-${{github.sha}}|" manifests/back.yaml

