name: Build, Push Frontend + Backend and Deploy to AKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build and push FRONTEND image
      - name: Build and Push Frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: docker.io/gassouma530975/frontend:v${{ github.run_number }}


      # Authenticate to AKS
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group myResourceGroup --name myAKSCluster --overwrite-existing

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image --namespace development deployment/frontend-deployment frontend=docker.io/gassouma530975/frontend:v${{ github.run_number }}
          

      # Wait for rollout
      - name: Wait for rollout
        run: |
          kubectl rollout statu --namespace development deployment/frontend-deployment

