name: Build, Push Frontend + Backend and Deploy to AKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4



      # Authenticate to AKS
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group myResourceGroup --name myAKSCluster --overwrite-existing

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image --namespace development deployment/frontend-deployment frontend=docker.io/gassouma530975/testdeploy:front
          kubectl set image --namespace deployment/backend-deployment backend=docker.io/gassouma530975/testdeploy:back

      # Wait for rollout
      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/frontend-deployment
          kubectl rollout status deployment/backend-deployment
