name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push FRONTEND image
      - name: Build and Push Frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: docker.io/gassouma530975/testdeploy:frontendv${{ github.run_number }}
  deploy:
    needs: build  
    runs-on: self-hosted
    steps:
      # Authenticate to AKS
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group myResourceGroup --name myAKSCluster --overwrite-existing
      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          
          kubectl set image --namespace development deployment/frontend-deployment frontend=docker.io/gassouma530975/testdeploy:frontendv${{ github.run_number }}

      # Wait for rollout
      - name: Wait for rollout
        run: |

          kubectl rollout status --namespace development deployment/frontend-deployment
